export const SET_USERNAME = "SET_USERNAME";
export const SET_STATE = "SET_STATE";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const SELECT_PROJECT = "SELECT_PROJECT";
export const FILTER_PROJECT = "FILTER_PROJECT";
export const SET_DISPLAY_CONDITIONS = "SET_DISPLAY_CONDITIONS";
export const FILTER_DISPLAY = "FILTER_DISPLAY";