export const HOST_NAME = 'http://localhost:8080';
export const INVALID_USERNAME = "INVALID_USERNAME";
export const WRONG_PASSWORD = "WRONG_PASSWORD";
export const SINGLE_DATE_CALENDAR = "SINGLE_DATE_CALENDAR";
export const SINGLE_DATE_ADD_EVENT = "SINGLE_DATE_ADD_EVENT";
export const SINGLE_DATE_EVENT_CALENDAR = "SINGLE_DATE_EVENT_CALENDAR";