export const HOST_NAME = process.env.REACT_APP_HOST_NAME;
export const INVALID_USERNAME = "INVALID_USERNAME";
export const WRONG_PASSWORD = "WRONG_PASSWORD";
export const OVERALL_CALENDAR = "OVERALL_CALENDAR";
export const SINGLE_DATE_CALENDAR = "SINGLE_DATE_CALENDAR";
export const LABEL_ITEM = "LABEL_ITEM";
export const PROJECT_ITEM = "PROJECT_ITEM";
